name: Update github myprofile

on: 'page_build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        python3 ./github_myprofile_updater/update.py
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "chenxieyuanli@hotmail.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/Chen-Xieyuanli/Chen-Xieyuanli.github.io.git"
        git add README.md
        git add images
        git diff --cached --quiet && echo "No profile updates to commit." && exit 0
        git commit -m "update my description automatically"
        git push "${remote_repo}" HEAD:main
